# Model module
_target_: track.model.model.DeepVelModel
_recursive_: false

# Parameters for the model
n_in_channels: 10
n_out_channels: 2
n_conv_layers: 20
n_filters: 64
kernel_size: 3
stride: 1

# Activation function
activation:
  # Module
  _target_: torch.nn.ReLU

# Optimizer
optimizer:
  # Function
  _target_: torch.optim.Adam
  # Learning rate
  lr: 1.e-3

# Loss term(s)
loss_func:
  # Function
  _target_: track.model.loss.MSE