# Model module
_target_: track.model.model.DeepVelUModel
_recursive_: false

# Model architecture
model:

# Activation function
activation:
  # Module
  _target_: torch.nn.ReLU

# Optimizer
optimizer:
  # Function
  _target_: torch.optim.Adam
  # Learning rate
  lr: 1.e-3

# Loss term(s)
loss_func:
  # Function
  _target_: track.model.loss.MSE