# Model module
_target_: track.model.model.DeepVelModel
_recursive_: False  # Do not recursively instantiate
n_in_channels: 10
n_out_channels: 2
n_conv_layers: 20
n_filters: 64
kernel_size: 3
stride: 1
activation:
  _target_: torch.nn.ReLU  # Activation function

# Optimizer
optimizer:
  _target_: torch.optim.Adam  # Optimizer function
  _partial_: True  # Partial initialization
  lr: 1.e-4  # Learning rate

# Loss term(s)
loss_func:
  _target_: track.model.loss.mse  # Loss function
  _partial_: True  # Partial initialization