# Locate/extract needed data
colocate:
  # Identify training patches
  train:
    # Function
    _target_: inverse.data.preparation.colocate.colocate
    _recursive_: false  # Do not instantiate nested objects
    # Input
    input:
      # Number of samples
      n_samples: 32000
      # Split (fractions of n_samples for training, validation, and test sets)
      split:
        train: 24000
        valid: 8000
      # Size of patches
      size: [48, 48]
      # Dimensions of the dataset
      nx: ${data.MURaMQS.I500.properties.nx}
      ny: ${data.MURaMQS.I500.properties.ny}
      nt: ${data.MURaMQS.I500.properties.nt}
      # Range of timesteps to choose from
      t_range: [0, 300]
      # Timesteps between samples (0 = same timestep, 1 = next timestep, etc.)
      dt: [0, 1]
    # Output
    output:
      # Path
      path: ${hydra.run.dir}/patches_train.pkl
      type: "file"