# Note: The order of defaults determines the order in which configs override each other.
defaults:
  - hydra: default
  - paths: default
  - data: MURaMQS
  - preparation: default
  - loader: default
  - model: DeepVel
  - trainer: gpu
  - callbacks: default
  - logger: default
  - _self_

# Task name. Note that it determines the output directory path
task_name: "default"  # Experiment
task_seed: 3210  # For reproducibility

paths:
  task_dir: "../tracking_outputs"
  run_id: "version_001"
  data_dir: "E:\\Data/ISSI_Team_Flows/Matthias/SSD_25x8Mm_16_pdmp_1_ISSI_Flows/2D"