# Use multiple loggers at once

# Loggers to combine
defaults:
  - mlflow
  - tensorboard
  - wandb

# Global parameters
name: ${task_name}  # Name of the logging instance
offline: True  # Whether to log offline
ui: True  # Whether to open the UI after logging