wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger  # Lightning logger
  save_dir: ${paths.log_dir} # Default directory where to save logs
  project: "tracking"  # Name of the project
  name: "tracking-training"  # Name of the logging instance
offline: True  # Whether to log offline
ui: True  # Whether to open the UI after logging